<?php

/**
 * @file
 * Contains matukio_user.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function matukio_user_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the matukio_user module.
    case 'help.page.matukio_user':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('User registration etc') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function matukio_user_theme() {
  $theme = [];

  return $theme;
}
